#!/usr/bin/env python3
"""Generate area report HTML files — Batch 3: Rockhampton, Newcastle, Launceston"""

import os, sys
sys.path.insert(0, os.path.dirname(__file__))
from generate_reports_1 import (
    CSS, JS_CHARTS_AND_MAP,
    infra_status_class, pop_counter_attrs, map_pts_js, map_line_js,
    build_loc_stat_panels, build_amenity_card, build_infra_cards,
    build_conditions, build_perf_rows, build_tags, build_risks,
    generate_html, OUT_DIR,
)

MARKETS = [

  # ── 7. ROCKHAMPTON ──────────────────────────────────────────────────────────
  dict(
    filename='rockhampton.html',
    key='rockhampton',
    city='Rockhampton',
    state_badge='Queensland',
    subtitle="Queensland's beef capital · 650km north of Brisbane · Central QLD's service hub",
    loc_stats=[
      ('650km',       'Brisbane CBD'),
      ('1hr 10min',   'By air to Brisbane'),
      ('200km',       'Gladstone'),
      ('Service Hub', 'For central QLD'),
    ],
    loc_copy=(
      'Rockhampton is the administrative and commercial capital of Central Queensland, 650km north '
      'of Brisbane on the Fitzroy River. Known as Australia\'s Beef Capital, the city is the hub '
      'of one of the world\'s largest cattle industries, while also serving as the regional centre '
      'for government services, healthcare, education and retail across a vast central Queensland '
      'catchment. CQUniversity\'s main campus is headquartered in Rockhampton, and the city hosts '
      'the region\'s principal public hospital.'
    ),
    education=[
      'CQUniversity (national HQ campus)',
      'Rockhampton Grammar School',
      'Cathedral College',
      "St Ursula's College",
    ],
    healthcare=[
      'Rockhampton Base Hospital (380+ beds)',
      'Mater Hospital Rockhampton',
      'BMI The Park Private Hospital',
      'Central QLD health network',
    ],
    retail=[
      'Stockland Rockhampton',
      'The Caves retail precinct',
      'East Street dining strip',
      'Quay Street riverside precinct',
    ],
    transport=[
      'Rockhampton Airport (Brisbane direct)',
      'Capricorn Highway (west to mines)',
      'Bruce Highway (north–south)',
      'Spirit of Queensland rail service',
    ],
    infra_total='$950M+',
    infra_cards=[
      dict(
        value='$750M+',
        title='Rockhampton Base Hospital Expansion',
        desc='Major multi-stage expansion of the principal public hospital for central Queensland, significantly expanding capacity and attracting specialist health professionals to the region. A permanent, government-funded employment anchor.',
        status='Committed',
      ),
      dict(
        value='Ongoing',
        title='CQUniversity Campus Redevelopment',
        desc='Ongoing investment in Rockhampton\'s flagship CQUniversity campus — the national headquarters of Australia\'s largest regional university by student numbers — supporting the city\'s knowledge economy transition.',
        status='Active',
      ),
      dict(
        value='$200M+',
        title='Fitzroy River Bridge Replacement',
        desc='Replacement of aging Fitzroy River bridge infrastructure, critical for connectivity between north and south Rockhampton and long-term urban growth across both sides of the river.',
        status='Planning approved',
      ),
    ],
    macro_copy=(
      "Rockhampton's economy is anchored by beef production and processing, government services, "
      'healthcare and education. CQUniversity — headquartered in Rockhampton — is one of '
      'Australia\'s largest universities by student numbers, creating a consistent renter base. '
      'The city has historically offered some of Australia\'s highest gross rental yields due to '
      'its affordability and the income levels generated by the surrounding agricultural and '
      'resources economy.'
    ),
    macro_copy_p2=(
      'The $750M+ Rockhampton Base Hospital expansion is the single largest infrastructure '
      'commitment in the city\'s history — it will materially expand healthcare employment and '
      'attract specialist medical professionals to the region on a permanent basis, creating '
      'a new high-quality renter cohort in a market that already offers exceptional yield.'
    ),
    comparable_text=(
      "Rockhampton's income-first market profile — high yield, stable essential services "
      'employment, affordable entry — shares characteristics with markets such as Dubbo and '
      'Toowoomba at earlier stages of their infrastructure investment cycles. '
      'Past performance in those markets is not a guide to future performance in Rockhampton.'
    ),
    affordability_text=(
      'At ~$370k median, Rockhampton offers the highest indicative gross yield profile of any '
      'market in this report at this entry point. The combination of an essential services '
      'employer base, a major university and a committed hospital expansion creates genuine, '
      'structural rental demand at a price level that most east-coast investors would find '
      'difficult to match anywhere close to their home market.'
    ),
    investment_intro=(
      'Rockhampton is the clearest income-first market in our current research coverage. '
      'The yield profile is exceptional at current prices, and the employment base — hospital, '
      'university, government, beef industry — is about as diversified and resilient as '
      'you\'ll find in a city of this size.'
    ),
    tags=[
      'Highest gross yield in this report at entry price',
      'Essential services and university employment anchor',
      'Beef industry income underpinning local economy',
      'Very affordable absolute entry point',
      'Long-term hold for income-focused strategy',
      'Uncorrelated to capital city market cycles',
    ],
    entry_house='$290k–$440k+',
    entry_unit='$185k–$280k+',
    risks=[
      (
        'Beef industry exposure',
        "A significant portion of Rockhampton's economy is linked to cattle production and "
        'processing. Prolonged drought, disease events or market disruptions can reduce '
        'agricultural income across the region, affecting employment and spending — though the '
        'hospital and university employment base provides a structural floor.',
      ),
      (
        'Flood risk',
        'Rockhampton has historically experienced flooding along the Fitzroy River. Properties '
        'in flood-prone areas require careful due diligence, appropriate insurance, and may be '
        'subject to land-use restrictions. Property selection and local due diligence are '
        'critical to managing this risk.',
      ),
      (
        'Capital growth ceiling',
        'At current price levels, capital growth will be driven primarily by infrastructure '
        'investment and employment growth rather than affordability arbitrage. Investors should '
        'calibrate expectations — this is primarily an income market with secondary growth '
        'characteristics driven by the hospital and university investment pipeline.',
      ),
    ],
    lukes_p1=(
      'Rockhampton is the clearest income-first market in our current research coverage. '
      'The yield profile is exceptional at current prices, and the employment base — hospital, '
      'university, government, beef industry — is about as diversified and resilient as '
      'you\'ll find in a city of this size. The $750M+ hospital expansion is a genuine '
      'game-changer for the quality of the local renter base.'
    ),
    lukes_p2=(
      'I look for properties here that serve the professional and healthcare renter base — '
      'not because one tenant type is better than another, but because professional renters '
      'tend to have longer tenancies and more predictable rental behaviour. The right '
      'property, in a location that appeals to that profile, delivers a very strong income '
      'position that is genuinely hard to replicate at this price point anywhere else in Australia.'
    ),
    map_center=[-23.380, 150.510],
    map_zoom=12,
    map_pts=[
      dict(latlng=[-23.380, 150.510], label='Rockhampton CBD',       color='#bd7a70', perm=True),
      dict(latlng=[-23.371, 150.501], label='CQUniversity',          color='#cf9b92', perm=False),
      dict(latlng=[-23.364, 150.511], label='Rockhampton Hospital',  color='#cf9b92', perm=False),
      dict(latlng=[-23.383, 150.476], label='Rockhampton Airport',   color='#cf9b92', perm=False),
    ],
    map_line=None,
    lga_name='Rockhampton Regional LGA',
    heroPrice='~$399k', heroYield='6.4–6.9%', heroPopulation='82k', heroVacancy='1.2%',
    houseMedian=399000, unitMedian=270000,
    houseRentRange='$475–$510', unitRentRange='$345–$375',
    houseYieldRange='6.2–6.7%', unitYieldRange='6.6–7.2%',
    vacancyRate=1.2, daysOnMarket=25, clearanceRate=44, propertiesListed=480,
    popTotal=82000, popGrowth=0.9, medianAge=35, ownerOccupier=62, employed=60, unemployment=5.5,
    conditions=[
      ('Rental demand',              'High',     72),
      ('Stock on market',            'Moderate', 42),
      ('Buyer competition',          'Moderate', 52),
      ('Infrastructure pipeline',    'Moderate', 60),
      ('Population growth momentum', 'Moderate', 50),
    ],
    housePerf=[('1 year', 9.9, 99), ('3 years', 14.0, 100), ('5 years', 9.0, 90), ('10 years', 4.8, 48)],
    unitPerf= [('1 year',  9.0,  90), ('3 years', 12.5, 100), ('5 years', 8.0, 80), ('10 years', 4.0, 40)],
    data_sources=(
      'ABS Regional Population &amp; Census &nbsp;&middot;&nbsp; Infrastructure Australia Pipeline '
      '&nbsp;&middot;&nbsp; Queensland Government Major Projects Register &nbsp;&middot;&nbsp; '
      'SQM Research &nbsp;&middot;&nbsp; CoreLogic / Suburbtrends &nbsp;&middot;&nbsp; '
      'Rockhampton Regional Council &nbsp;&middot;&nbsp; Map data &copy; OpenStreetMap contributors'
    ),
  ),

  # ── 8. NEWCASTLE ────────────────────────────────────────────────────────────
  dict(
    filename='newcastle.html',
    key='newcastle',
    city='Newcastle',
    state_badge='New South Wales',
    subtitle="Australia's seventh-largest city · 170km north of Sydney · Hunter Valley's capital",
    loc_stats=[
      ('170km',         'Sydney CBD'),
      ('~2.5hr',        'NSW TrainLink to Sydney'),
      ('30km',          'Hunter Valley wine region'),
      ("Australia's 7th",'Largest city'),
    ],
    loc_copy=(
      'Newcastle sits at the mouth of the Hunter River, 170km north of Sydney, and is '
      'Australia\'s seventh-largest city. Connected to Sydney by both the Hunter/Central Coast '
      'rail line and the Pacific Motorway, Newcastle has undergone a substantial economic '
      'transformation from its historical steel and coal roots into a diversified city anchored '
      'by the University of Newcastle, John Hunter Hospital, a growing professional services '
      'sector and a vibrant creative and hospitality economy. The CBD\'s light rail and '
      'waterfront urban renewal have fundamentally repositioned the city\'s liveability offer.'
    ),
    education=[
      'University of Newcastle (38,000+ students)',
      'TAFE NSW Hunter',
      'Newcastle Grammar School',
      'Hunter Valley Grammar School',
    ],
    healthcare=[
      'John Hunter Hospital (700+ beds, major teaching)',
      'Calvary Mater Newcastle',
      'Hunter New England Health (district HQ)',
      'Newcastle Private Hospital',
    ],
    retail=[
      'Hunter Street Mall (CBD)',
      'Darby Street lifestyle strip',
      'The Junction retail and dining',
      'Honeysuckle waterfront precinct',
    ],
    transport=[
      'NSW TrainLink (2.5hr to Sydney)',
      'Newcastle Light Rail (CBD connector)',
      'Pacific Motorway (Sydney direct)',
      'Newcastle Airport (25km, domestic)',
    ],
    infra_total='$2B+',
    infra_cards=[
      dict(
        value='$1.5B+',
        title='Hunter Park Urban Renewal',
        desc='Major regeneration of the former steelworks precinct at Mayfield — one of Australia\'s largest urban renewal projects — delivering new residential, commercial and open space across a significant inner-city site with direct waterfront access.',
        status='Under development',
      ),
      dict(
        value='TBC',
        title='Newcastle Light Rail Stage 2 Planning',
        desc='Planning for extension of the existing light rail network to expand access across the inner city, building on Stage 1\'s success and further connecting established suburbs to the waterfront precinct and employment corridors.',
        status='Planning',
      ),
      dict(
        value='$500M+',
        title='University of Newcastle Investment',
        desc='Significant ongoing capital investment in the Callaghan and NUSpace city campuses, supporting Newcastle\'s position as a major research and education city and driving a growing student rental demand in the inner ring.',
        status='Active',
      ),
    ],
    macro_copy=(
      "Greater Newcastle's economy has diversified substantially over the past two decades. "
      'The University of Newcastle is the single largest employer, followed by John Hunter '
      'Hospital and Hunter New England Health. The professional services sector has grown '
      'significantly as Sydney businesses establish satellite operations in the region.'
    ),
    macro_copy_p2=(
      'Population growth is steady, driven by lifestyle migration from Sydney and a growing '
      'student population. The demographic profile is younger and more diverse than most '
      'regional markets, reflecting both the university\'s influence and the city\'s growing '
      'appeal to young professionals seeking Sydney-adjacent lifestyle without Sydney pricing.'
    ),
    comparable_text=(
      'Newcastle\'s trajectory — from industrial city to knowledge economy, driven by university '
      'growth, urban renewal and Sydney proximity — shares characteristics with Wollongong\'s '
      'transformation over the preceding decade. The waterfront and light rail investment mirrors '
      'what has driven sustained price growth in comparable Australian urban renewal precincts. '
      'Past performance is not a guide to future performance.'
    ),
    affordability_text=(
      'At ~$820k median, Newcastle has repriced significantly from its industrial-era values '
      'and now represents a premium over many regional markets. The premium reflects genuine '
      'liveability, Sydney proximity and employment diversification — factors that have '
      'underpinned sustained demand even through Sydney\'s market cycles.'
    ),
    investment_intro=(
      'Newcastle is a fully established regional city with genuine liveability credentials, a '
      'diversified employment base, and a trajectory from industrial to knowledge economy that '
      'is still playing out — creating medium-term growth potential alongside solid yield in '
      'the inner ring and university precinct.'
    ),
    tags=[
      'Established city, genuine liveability credentials',
      'University and hospital employment anchors',
      'Sydney proximity creates strong demand floor',
      'Urban renewal driving long-term value uplift',
      'Diversified economy reducing investment risk',
      'Long-term capital growth alongside solid yield',
    ],
    entry_house='$700k–$1.0M+',
    entry_unit='$490k–$680k+',
    risks=[
      (
        'Higher entry price, lower yield',
        "Newcastle's success has partially repriced it. Entry costs are meaningfully higher than "
        'most other markets in this report, and gross yields are lower as a result. The case '
        'here is more capital growth than income — investors focused on yield should consider '
        'other markets in this report.',
      ),
      (
        'Sydney market correlation',
        "Newcastle's price trajectory is partly influenced by Sydney's market cycle. When Sydney "
        'cools, Newcastle tends to follow with a lag. This correlation means less diversification '
        'benefit for investors already holding Sydney property.',
      ),
      (
        'New supply in growth corridors',
        "The Hunter's northern and western corridors are experiencing residential development. "
        'Monitor new supply levels in growth areas, which can suppress yield and slow price '
        'recovery in softer market conditions — established inner-ring properties are more '
        'insulated from this pressure.',
      ),
    ],
    lukes_p1=(
      'Newcastle has already had its rerating — anyone who bought in 2015 has done well. '
      'The question I answer for clients now is whether there is still a case at current '
      'prices. There is, but with much tighter selection than five years ago. The pockets '
      'that still make sense are where the full benefit of the transformation has not yet '
      'been priced in — those pockets exist, they are just not the obvious ones.'
    ),
    lukes_p2=(
      'The trade-off in Newcastle is that the capital growth thesis is stronger than the '
      'income thesis at current prices. Yields have compressed as the market has matured. '
      'A slightly lower-yielding property in a genuinely constrained inner-ring pocket '
      'outperforms a higher-yield outer suburb over the medium term. Newcastle rewards '
      'precise selection more than any other market on this list.'
    ),
    map_center=[-32.920, 151.780],
    map_zoom=11,
    map_pts=[
      dict(latlng=[-32.925, 151.770], label='Newcastle CBD',          color='#bd7a70', perm=True),
      dict(latlng=[-32.895, 151.697], label='University of Newcastle', color='#cf9b92', perm=False),
      dict(latlng=[-32.904, 151.691], label='John Hunter Hospital',    color='#cf9b92', perm=False),
      dict(latlng=[-32.927, 151.786], label='Honeysuckle Waterfront',  color='#cf9b92', perm=False),
      dict(latlng=[-33.869, 151.209], label='Sydney CBD',              color='#cf9b92', perm=False),
    ],
    map_line=([-33.869, 151.209], [-32.925, 151.770]),
    lga_name='Greater Newcastle LGA',
    heroPrice='~$865k', heroYield='3.3–3.8%', heroPopulation='340k', heroVacancy='1.6%',
    houseMedian=865000, unitMedian=955000,
    houseRentRange='$535–$565', unitRentRange='$675–$720',
    houseYieldRange='3.2–3.5%', unitYieldRange='3.7–4.0%',
    vacancyRate=1.6, daysOnMarket=25, clearanceRate=62, propertiesListed=1480,
    popTotal=340000, popGrowth=1.6, medianAge=38, ownerOccupier=61, employed=63, unemployment=4.2,
    conditions=[
      ('Rental demand',              'High',      75),
      ('Stock on market',            'Moderate',  38),
      ('Buyer competition',          'High',      72),
      ('Infrastructure pipeline',    'Very High', 88),
      ('Population growth momentum', 'Strong',    70),
    ],
    housePerf=[('1 year', 14.6, 100), ('3 years', 6.8, 68), ('5 years', 9.0, 90), ('10 years', 8.5, 85)],
    unitPerf= [('1 year', 2.2, 22), ('3 years', 5.5, 55), ('5 years', 7.2, 72), ('10 years', 6.8, 68)],
    data_sources=(
      'ABS Regional Population &amp; Census &nbsp;&middot;&nbsp; Infrastructure Australia Pipeline '
      '&nbsp;&middot;&nbsp; NSW Government Major Projects Register &nbsp;&middot;&nbsp; '
      'SQM Research &nbsp;&middot;&nbsp; CoreLogic / Suburbtrends &nbsp;&middot;&nbsp; '
      'City of Newcastle &nbsp;&middot;&nbsp; Map data &copy; OpenStreetMap contributors'
    ),
  ),

  # ── 9. LAUNCESTON ───────────────────────────────────────────────────────────
  dict(
    filename='launceston.html',
    key='launceston',
    city='Launceston',
    state_badge='Tasmania',
    subtitle="Tasmania's second city · 200km north of Hobart · Tamar Valley gateway",
    loc_stats=[
      ('200km',    'Hobart'),
      ('2hr 15min','By road to Hobart'),
      ('45min',    'By air to Melbourne'),
      ('#2',       'Largest city in TAS'),
    ],
    loc_copy=(
      'Launceston sits at the confluence of the North and South Esk rivers at the head of the '
      'Tamar Valley estuary, 200km north of Hobart. As Tasmania\'s second city, Launceston '
      'serves as the commercial, educational and healthcare centre for northern Tasmania and has '
      'experienced sustained population and economic growth as the state has emerged as a '
      'lifestyle migration destination for mainland Australians. The city is served by '
      'Launceston Airport with direct flights to Melbourne, Sydney and Brisbane.'
    ),
    education=[
      'University of Tasmania (Launceston campus)',
      'TAFE Tasmania North',
      'Launceston Church Grammar School',
      'Scotch Oakburn College',
    ],
    healthcare=[
      'Launceston General Hospital (350+ beds)',
      "St Luke's Hospital Launceston",
      'Northern Midlands health network',
      'Comprehensive specialist services',
    ],
    retail=[
      'Launceston Central shopping centre',
      'Kmart Plaza',
      'Quadrant Mall precinct',
      'Seaport waterfront dining precinct',
    ],
    transport=[
      'Launceston Airport (Melbourne/Sydney/Brisbane)',
      'Bass Highway (west)',
      'Midland Highway (Hobart, 2hr)',
      'Metro Tasmania local network',
    ],
    infra_total='$940M+',
    infra_cards=[
      dict(
        value='$600M+',
        title='Launceston General Hospital Redevelopment',
        desc='Major expansion of northern Tasmania\'s principal hospital — the second-largest public hospital in the state — expanding capacity for the growing northern Tasmanian population. A committed, government-funded employment anchor.',
        status='Committed',
      ),
      dict(
        value='$250M+',
        title='University of Tasmania Launceston Investment',
        desc='Significant capital investment in UTAS\'s northern campus, expanding teaching and research capacity and supporting Launceston\'s knowledge economy transition and student population growth.',
        status='Active',
      ),
      dict(
        value='$90M+',
        title='Launceston City Deal',
        desc='Urban renewal investment focused on waterfront, arts, tourism and community infrastructure across the Launceston CBD — supporting the city\'s positioning as a genuine lifestyle destination beyond its regional service function.',
        status='Active',
      ),
    ],
    macro_copy=(
      'Northern Tasmania has experienced a structural shift in recent years as lifestyle '
      'migration from mainland Australia has compressed vacancy rates, pushed rents higher '
      'and attracted a new professional demographic to the region. Launceston offers '
      'Melbourne-adjacent lifestyle amenity — wineries, outdoor recreation, arts culture — '
      'at a fraction of the cost, supported by direct flights from three major capitals.'
    ),
    macro_copy_p2=(
      'The Launceston General Hospital and University of Tasmania provide a structural '
      'employment base that exists independently of the lifestyle migration story. These two '
      'institutions together employ thousands of Tasmanians and attract professionals from '
      'the mainland who then rent in the city on long-term arrangements.'
    ),
    comparable_text=(
      "Launceston's lifestyle migration story — mainland professionals seeking Tasmanian quality "
      'of life with direct capital city flight access — shares characteristics with what Hobart '
      'experienced in 2015–2018 before the broader market repriced. Northern Tasmania\'s '
      'structural supply constraints remain largely intact. Past performance is not a guide '
      'to future performance.'
    ),
    affordability_text=(
      'At ~$490k median, Launceston offers meaningful affordability relative to Hobart (~$760k) '
      'while sharing many of the same structural supply dynamics. For investors seeking Tasmanian '
      'exposure at a lower entry point, Launceston\'s income profile is stronger and the growth '
      'potential relative to price remains compelling.'
    ),
    investment_intro=(
      'Launceston offers an attractive income-and-growth combination for investors willing to look '
      'beyond the mainland. Structural rental undersupply, strong lifestyle migration and '
      'significant hospital and university investment underpin both yield and long-term '
      'capital growth in a market with genuine physical supply constraints.'
    ),
    tags=[
      'Strong lifestyle migration demand',
      'Hospital and university employment anchors',
      'Structurally undersupplied rental market',
      'High gross yield relative to entry price',
      'Direct flights to three mainland capitals',
      'Long-term capital growth compounding',
    ],
    entry_house='$420k–$620k+',
    entry_unit='$270k–$400k+',
    risks=[
      (
        'Lifestyle migration dependency',
        'A meaningful portion of recent growth has been driven by mainland lifestyle migration. '
        'If this trend moderates (e.g., sustained return-to-office requirements), demand from '
        'this cohort may soften — though the hospital and university employment base provides '
        'a stable structural demand floor.',
      ),
      (
        'Limited local employment depth',
        'Outside healthcare, education and government, Launceston\'s private sector employment '
        'base is relatively narrow. Rental demand from local employment is stable but the '
        'capacity for growth is limited by local wage levels and job creation pace.',
      ),
      (
        'Tasmania-specific investment considerations',
        'Some lenders and insurers apply specific criteria to Tasmanian property investments. '
        'Ensure financing arrangements are confirmed prior to purchase, and that insurance is '
        'available at competitive rates for the specific property type and location.',
      ),
    ],
    lukes_p1=(
      'Launceston is a market I\'ve watched evolve from a relative backwater to a genuinely '
      'compelling investment destination over the past decade. The lifestyle migration story '
      'is real and sustainable — people who discover northern Tasmania tend not to leave, '
      'and that creates durable rental demand from a high-quality tenant cohort that '
      'looks after properties and stays for extended periods.'
    ),
    lukes_p2=(
      'The hospital and university employment base provides a structural rental floor that '
      'exists independently of the lifestyle migration story. These are the two things I '
      'look for in any regional market — a lifestyle draw that fills the pipeline, and a '
      'structural employment anchor that keeps it full when the trend moderates. '
      'Launceston has both, at an entry price that still makes sense.'
    ),
    map_center=[-41.440, 147.140],
    map_zoom=12,
    map_pts=[
      dict(latlng=[-41.440, 147.140], label='Launceston CBD',          color='#bd7a70', perm=True),
      dict(latlng=[-41.460, 147.152], label='Launceston General Hosp', color='#cf9b92', perm=False),
      dict(latlng=[-41.455, 147.148], label='UTAS Launceston',         color='#cf9b92', perm=False),
      dict(latlng=[-41.545, 147.214], label='Launceston Airport',      color='#cf9b92', perm=False),
      dict(latlng=[-42.880, 147.330], label='Hobart',                  color='#cf9b92', perm=False),
    ],
    map_line=None,
    lga_name='City of Launceston',
    heroPrice='~$590k', heroYield='4.5–4.7%', heroPopulation='80k', heroVacancy='0.6%',
    houseMedian=590000, unitMedian=430000,
    houseRentRange='$495–$525', unitRentRange='$380–$410',
    houseYieldRange='4.3–4.7%', unitYieldRange='4.6–5.0%',
    vacancyRate=0.6, daysOnMarket=42, clearanceRate=60, propertiesListed=420,
    popTotal=80000, popGrowth=1.2, medianAge=40, ownerOccupier=62, employed=60, unemployment=5.0,
    conditions=[
      ('Rental demand',              'Very High', 85),
      ('Stock on market',            'Low',       22),
      ('Buyer competition',          'High',      72),
      ('Infrastructure pipeline',    'Moderate',  58),
      ('Population growth momentum', 'Moderate',  55),
    ],
    housePerf=[('1 year', 15.7, 100), ('3 years', 7.8, 78), ('5 years', 10.2, 100), ('10 years', 8.8, 88)],
    unitPerf= [('1 year', 2.8, 28), ('3 years', 6.5, 65), ('5 years', 8.5,   85), ('10 years', 7.2, 72)],
    data_sources=(
      'ABS Regional Population &amp; Census &nbsp;&middot;&nbsp; Infrastructure Australia Pipeline '
      '&nbsp;&middot;&nbsp; Tasmanian Government Major Projects Register &nbsp;&middot;&nbsp; '
      'SQM Research &nbsp;&middot;&nbsp; CoreLogic / Suburbtrends &nbsp;&middot;&nbsp; '
      'City of Launceston &nbsp;&middot;&nbsp; Map data &copy; OpenStreetMap contributors'
    ),
  ),

]

if __name__ == '__main__':
    os.makedirs(OUT_DIR, exist_ok=True)
    for m in MARKETS:
        html = generate_html(m)
        path = os.path.join(OUT_DIR, m['filename'])
        with open(path, 'w', encoding='utf-8') as f:
            f.write(html)
        print(f'  Generated: reports/{m["filename"]}')
    print(f'\nDone. {len(MARKETS)} files written.')
